spring:
  profiles:
    active: secrets
  application:
    name: store
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 10000
        linger:
          ms: 0
        request:
          timeout:
            ms: 5000
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

application:
  notices:
    health: UP
  url:
    wallet:
      stub_pay_order: http://localhost:8081/api/v1/wallet/stubPayOrder