name: mvn clean compile

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  delivery:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Compile and Test Project 1
        run: |
          cd delivery
          mvn -B clean compile test

  store:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Compile and Test Project 2
        run: |
          cd store
          mvn -B clean compile test

  wallet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Compile and Test Project 3
        run: |
          cd wallet
          mvn -B clean compile test